[package]
name = "mimiron_bot"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["Abdul Rahman Sibahi <a.sibahi@gmail.com"]
description = "A Discord bot to query Blizzard Hearthstone API"
license = "MIT"

[dependencies]
mimiron = { path = "../mimiron" }
anyhow = "1.0.68"
poise = "0.5.2"
shuttle-poise = "0.29.0"
shuttle-runtime = "0.29.0"
shuttle-secrets = "0.29.0"
tracing = "0.1.37"
tokio = "1.26.0"
