[package]
name = "mimiron_bot"
version = "0.2.0"
edition = "2021"
publish = false
authors = ["Abdul Rahman Sibahi <a.sibahi@gmail.com"]
description = "A Discord bot to query Blizzard Hearthstone API"
license = "MIT"

[dependencies]
mimiron = { path = "../mimiron" }
anyhow = "1"
poise = "0.6.0"
shuttle-serenity = { version = "0.34.1", default-features = false, features = [
    "serenity-0-12-rustls_backend",
] }
shuttle-runtime = "0.34.1"
shuttle-secrets = "0.34.1"
tracing-subscriber = "0.3.18"
tokio = "1"
itertools = "0.12.0"
image = { version = "0.24.7", default-features = false, features = [
    "png",
    "jpeg_rayon",
] }
urlencoding = "2.1.3"
