[package]
name = "mimiron_bot"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["Abdul Rahman Sibahi <a.sibahi@gmail.com"]
description = "A Discord bot to query Blizzard Hearthstone API"
license = "MIT"

[dependencies]
mimiron = { path = "../mimiron" }
anyhow = "1.0.68"
poise = "0.5.2"
shuttle-poise = "0.34"
shuttle-runtime = "0.34"
shuttle-secrets = "0.34"
tracing = "0.1.37"
tokio = "1.26.0"
itertools = "0.12.0"
image = { version = "0.24.7", default-features = false, features = [
    "png",
    "jpeg_rayon",
] }
urlencoding = "2.1.3"