[package]
name = "mimiron_bot"
version = "0.1.0"
edition = "2021"
authors = ["Abdul Rahman Sibahi <a.sibahi@gmail.com"]
description = "A Discord bot to query Blizzard Hearthstone API"
license = "MIT"

[dependencies]
mimiron = { path = "../mimiron" }

[[bin]]
name = "m1m1r0n"
path = "src/main.rs"