[workspace]

resolver = "2"
members = ["mimiron", "mimiron_cli", "mimiron_bot"]
default_members = ["mimiron", "mimiron_cli"]

[workspace.lints.clippy]
pedantic = "warn"
module_name_repetitions = "allow"

# no real reason unless officially released
missing_errors_doc = "allow" 
missing_panics_doc = "allow"
