[package]
name = "mimiron"
version = "0.2.0"
edition = "2021"
authors = ["Abdul Rahman Sibahi <a.sibahi@gmail.com"]
description = "A CLI application to query Blizzard Hearthstone API"
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
colored = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "2", features = ["json"] }
anyhow = "1"
base64 = "0.21"
dotenvy = "0.15"
itertools = "0.11.0"
counter = "0.5.7"
nom = "7.1.3"
textwrap = { version = "0.16.0", default-features = false, features = ["terminal_size"] }
image = "0.24"
directories = "5.0"
imageproc = "0.23"
rusttype = "0.9"
chrono = "0.4.26"
rayon = "1.7.0"
include_path = "0.1.1"
