[package]
name = "mimiron_cli"
version = "0.4.5"
edition = "2021"
authors = ["Abdul Rahman Sibahi <a.sibahi@gmail.com"]
description = "A CLI application to query Blizzard Hearthstone API"
license = "MIT"

[lints]
workspace = true

[dependencies]
mimiron = { path = "../mimiron" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
directories = "5.0"
chrono = "0.4.26"

[[bin]]
name = "mimiron"
path = "src/main.rs"
