[package]
name = "mimiron_cli"
version = "0.3.0"
edition = "2021"
authors = ["Abdul Rahman Sibahi <a.sibahi@gmail.com"]
description = "A CLI application to query Blizzard Hearthstone API"
license = "MIT"

[dependencies]
mimiron = { path = "../mimiron" }

[[bin]]
name = "mimiron"
path = "src/main.rs"