[package]
name = "mimiron"
version = "0.7.3"
edition = "2021"
authors = ["Abdul Rahman Sibahi <a.sibahi@gmail.com"]
description = "A library to query Blizzard Hearthstone API"
license = "MIT"

[lints]
workspace = true

[dependencies]
colored = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "2", features = ["json"] }
anyhow = "1"
base64 = "0.22"
dotenvy = "0.15"
itertools = "0.12.0"
counter = "0.5.7"
nom = "7.1.3"
textwrap = { version = "0.16.0", default-features = false, features = [
    "terminal_size",
] }
image = { version = "0.25", default-features = false, features = [
    "png",
    "jpeg",
    "rayon",
] }
imageproc = "0.24"
ab_glyph = "0.2.23"
rayon = "1.7.0"
eitherable = "0.1.0"
unicode-width = "0.1"
once_cell = "1.19"
cached = "0.51"
either = { version = "1.10", features = ["serde"] }
convert_case = "0.6.0"
integer-encoding = "4.0.0"
nucleo-matcher = "0.3.1"
