[package]
name = "mimiron"
version = "0.4.0"
edition = "2021"
authors = ["Abdul Rahman Sibahi <a.sibahi@gmail.com"]
description = "A library to query Blizzard Hearthstone API"
license = "MIT"

[lints]
workspace = true

[dependencies]
colored = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "2", features = ["json"] }
anyhow = "1"
base64 = "0.21"
dotenvy = "0.15"
itertools = "0.12.0"
counter = "0.5.7"
nom = "7.1.3"
textwrap = { version = "0.16.0", default-features = false, features = [
    "terminal_size", 
] }
image = { version = "0.24.7", default-features = false, features = [
    "png",
    "jpeg_rayon",
] }
imageproc = "0.23"
rusttype = "0.9"
rayon = "1.7.0"
eitherable = "0.1.0"
unicode-width = "0.1"
