name: Shuttle Deploy

on:
  push:
    branches:
      - master # i am an idiot. was wondering why this does not work.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01J7KG33CYR834R17X6064GP0W
